- name: Geoffrey H. Garrett
  email: g.h.garrett13@gmail.com
  aliases:
  - Geoffrey Hyde Garrett
  - Geoffrey Garrett
  - ggarrett13
- name: Emil Heeren
  email:
- name: FlyOHolic
  email: m.a.griffioen@student.tudelft.nl
- name: Reneh107
  email: r.hoogendoorn@student.tudelft.nl
  aliases:
    - Rene107
  alternate_emails:
    - renehoogendoorn107@hotmail.com
- name: Kartik Kumar
  email: me@kartikkumar.com
- name: Elmar Puts
  email: elmarputs@gmail.com
- name: Dominic Dirkx
  email: D.Dirkx@tudelft.nl
  aliases:
  - DominicDirkx
  alternate_emails:
  - hidden@hidden.com
  - d.dirkx@tudelft.nl
- name: mfacchinelli
  email: michele.facchinelli@yahoo.it
  aliases:
    - mfacchinelli
- name: Frank Hogervorst
  email: f.c.hogervorst@student.tudelft.nl
  aliases:
  - FrankHogervorst
- name: Aleix Pinardell
  email: J.A.PinardellPons@student.tudelft.nl
  alternate_emails:
    - aleixpinardell@gmail.com
- name: Jeroen Melman
  email: None
  alternate_emails:
  - hidden@hidden.com
- name: Michele Facchinelli
  email: m.facchinelli@student.tudelft.nl
- name: mchambe
  email: m.s.chambe@student.tudelft.nl
- name: mvandenbroeck
  email: m.m.h.vandenbroeck@student.tudelft.nl
- name: Jacco Geul
  email: jacco@geul.net
- name: ifodde
  email: I.Fodde@student.tudelft.nl
  alternate_emails:
  - iostofodde@gmail.com
- name: Rody Oldenhuis
  email: rody@dawnaerospace.com
- name: Alejandro Gonzalez Puerta
  email: a.gonzalezpuerta@student.tudelft.nl
- name: Valerio Filice
  email: filicevalerio@gmail.com
- name: Miguel Pignatelly Avillez
  email: mpignatelli.avillez@gmail.com
  aliases:
    - pipas
    - MiguelAvillez
- name: Filippo Oggionni
  email: filippo.oggionni@gmail.com
  aliases:
    - FilippoOggionni