# -------------------------------------------------
# Project created by QtCreator 2010-09-30T01:39:33
# -------------------------------------------------
QT -= gui core
TARGET = Tudat
CONFIG += console
CONFIG -= app_bundle
TEMPLATE = app
SOURCES += Applications/exampleEarthOrbitingSatellite.cpp \
    Astrodynamics/Bodies/planet.cpp \
    Astrodynamics/EnvironmentModels/exponentialAtmosphere.cpp \
    Astrodynamics/EnvironmentModels/tabulatedAtmosphere.cpp \
    Astrodynamics/EnvironmentModels/unitTestExponentialAtmosphere.cpp \
    Astrodynamics/EnvironmentModels/unitTestTabulatedAtmosphere.cpp \
    Astrodynamics/EnvironmentModels/centralGravityField.cpp \
    Astrodynamics/EnvironmentModels/sphericalHarmonicsGravityField.cpp \
    Astrodynamics/EnvironmentModels/unitTestSphericalHarmonicsGravityField.cpp \
    Astrodynamics/ForceModels/unitTestAerodynamicMomentAndAerodynamicForce.cpp \
    Astrodynamics/ForceModels/aerodynamics.cpp \
    Astrodynamics/ForceModels/aerodynamicCoefficientGenerator.cpp \
    Astrodynamics/ForceModels/hypersonicLocalInclinationAnalysis.cpp \
    Astrodynamics/ForceModels/unitTestAerodynamicsNamespace.cpp \
    Astrodynamics/ForceModels/unitTestCoefficientGenerator.cpp \
    Astrodynamics/MomentModels/aerodynamicMoment.cpp \
    Astrodynamics/physicalConstants.cpp \
    Astrodynamics/unitTestPhysicalConstants.cpp \
    Astrodynamics/Propagators/cartesianStateNumericalPropagator.cpp \
    Astrodynamics/Propagators/keplerPropagator.cpp \
    Astrodynamics/Propagators/seriesPropagator.cpp \
    Astrodynamics/Propagators/numericalPropagator.cpp \
    Astrodynamics/Propagators/unitTestNumericalPropagator.cpp \
    Astrodynamics/Propagators/unitTestKeplerPropagator.cpp \
    Astrodynamics/ReferenceFrames/referenceFrameTransformations.cpp \
    Astrodynamics/ReferenceFrames/unitTestReferenceFrameTransformations.cpp \
    Astrodynamics/States/approximatePlanetPositions.cpp \
    Astrodynamics/States/approximatePlanetPositionsBase.cpp \
    Astrodynamics/States/approximatePlanetPositionsCircularCoplanar.cpp \
    Astrodynamics/States/orbitalElementConversions.cpp \
    Astrodynamics/States/convertMeanAnomalyToEccentricAnomaly.cpp \
    Astrodynamics/States/convertMeanAnomalyToHyperbolicEccentricAnomaly.cpp \
    Astrodynamics/States/unitTestApproximatePlanetPositions.cpp \
    Astrodynamics/States/unitTestKeplerianElements.cpp \
    Astrodynamics/States/unitTestCartesianElements.cpp \
    Astrodynamics/States/unitTestOrbitalElementConversions.cpp \
    Astrodynamics/MissionSegments/escapeAndCapture.cpp \
    Astrodynamics/MissionSegments/gravityAssist.cpp \
    Astrodynamics/MissionSegments/lambertTargeter.cpp \
    Astrodynamics/MissionSegments/librationPoint.cpp \
    Astrodynamics/MissionSegments/unitTestDeepSpaceManeuver.cpp \
    Astrodynamics/MissionSegments/unitTestEscapeAndCapture.cpp \
    Astrodynamics/MissionSegments/unitTestGravityAssist.cpp \
    Astrodynamics/MissionSegments/unitTestLambertTargeter.cpp \
    Astrodynamics/MissionSegments/unitTestLibrationPoints.cpp \
    Basics/basicFunctions.cpp \
    Input/textFileReader.cpp \
    Input/fileReader.cpp \
    Input/twoLineElementData.cpp \
    Input/twoLineElementsTextFileReader.cpp \
    Input/unitTestTextFileReader.cpp \
    Input/unitTestTwoLineElementsTextFileReader.cpp \
    Mathematics/basicMathematicsFunctions.cpp \
    Mathematics/cubicSplineInterpolation.cpp \
    Mathematics/unitTestBasicMathematicsFunctions.cpp \
    Mathematics/unitTestCubicSplineInterpolation.cpp \
    Mathematics/GeometricShapes/compositeSurfaceGeometry.cpp \
    Mathematics/GeometricShapes/singleSurfaceGeometry.cpp \
    Mathematics/GeometricShapes/torus.cpp \
    Mathematics/GeometricShapes/sphereSegment.cpp \
    Mathematics/GeometricShapes/conicalFrustum.cpp \
    Mathematics/GeometricShapes/capsule.cpp \
    Mathematics/GeometricShapes/unitTestLawgsSurfaceGeometry.cpp \
    Mathematics/GeometricShapes/quadrilateralMeshedSurfaceGeometry.cpp \
    Mathematics/GeometricShapes/lawgsPartGeometry.cpp \
    Mathematics/LinearAlgebra/linearAlgebra.cpp \
    Mathematics/NumericalIntegrators/euler.cpp \
    Mathematics/NumericalIntegrators/integrator.cpp \
    Mathematics/NumericalIntegrators/rungeKutta4thOrderFixedStepsize.cpp \
    Mathematics/NumericalIntegrators/singleStepIntegrationMethods.cpp \
    Mathematics/NumericalIntegrators/unitTestRungeKutta4thOrderFixedStepsizeIntegrator.cpp \
    Mathematics/NumericalIntegrators/unitTestEulerIntegrator.cpp \
    Mathematics/RandomNumberGenerators/exponentialRandomNumberGenerator.cpp \
    Mathematics/RandomNumberGenerators/normalRandomNumberGenerator.cpp \
    Mathematics/RandomNumberGenerators/uniformRandomNumberGenerator.cpp \
    Mathematics/RandomNumberGenerators/unitTestRandomNumberGenerator.cpp \
    Mathematics/RootFindingMethods/unitTestNewtonRaphson.cpp \
    Mathematics/RootFindingMethods/newtonRaphson.cpp \
    Mathematics/Statistics/simpleLinearRegression.cpp \
    Mathematics/Statistics/unitTestSimpleLinearRegression.cpp \
    Mathematics/unitTestUnitConversions.cpp \
    Output/writingOutputToFile.cpp \
    #applicationMain.cpp
    unitTestMain.cpp
HEADERS += Applications/exampleEarthOrbitingSatellite.h \
    Astrodynamics/Bodies/body.h \
    Astrodynamics/Bodies/celestialBody.h \
    Astrodynamics/Bodies/planet.h \
    Astrodynamics/Bodies/vehicle.h \
    Astrodynamics/Bodies/vehicleExternalModel.h \
    Astrodynamics/EnvironmentModels/environmentModel.h \
    Astrodynamics/EnvironmentModels.h \
    Astrodynamics/EnvironmentModels/exponentialAtmosphere.h \
    Astrodynamics/EnvironmentModels/tabulatedAtmosphere.h \
    Astrodynamics/EnvironmentModels/unitTestExponentialAtmosphere.h \
    Astrodynamics/EnvironmentModels/unitTestTabulatedAtmosphere.h \
    Astrodynamics/EnvironmentModels/centralGravityField.h \
    Astrodynamics/EnvironmentModels.h \
    Astrodynamics/EnvironmentModels/sphericalHarmonicsGravityField.h \
    Astrodynamics/EnvironmentModels/unitTestSphericalHarmonicsGravityField.h \
    Astrodynamics/ForceModels/forceModel.h \
    Astrodynamics/ForceModels/aerodynamicForce.h \
    Astrodynamics/ForceModels/gravitationalForceModel.h \
    Astrodynamics/ForceModels/unitTestAerodynamicMomentAndAerodynamicForce.h \
    Astrodynamics/ForceModels/aerodynamics.h \
    Astrodynamics/ForceModels/aerodynamicCoefficientGenerator.h \
    Astrodynamics/ForceModels/aerodynamicCoefficientInterface.h \
    Astrodynamics/ForceModels/hypersonicLocalInclinationAnalysis.h \
    Astrodynamics/ForceModels/unitTestAerodynamicsNamespace.h \
    Astrodynamics/ForceModels/unitTestCoefficientGenerator.h \
    Astrodynamics/MomentModels/aerodynamicMoment.h \
    Astrodynamics/MomentModels/momentModel.h \
    Astrodynamics/physicalConstants.h \
    Astrodynamics/unitTestPhysicalConstants.h \
    Astrodynamics/Propagators/cartesianStateNumericalPropagator.h \
    Astrodynamics/Propagators/keplerPropagator.h \
    Astrodynamics/Propagators/propagatorDataContainer.h \
    Astrodynamics/Propagators/propagator.h \
    Astrodynamics/Propagators/seriesPropagator.h \
    Astrodynamics/Propagators/numericalPropagator.h \
    Astrodynamics/Propagators/unitTestNumericalPropagator.h \
    Astrodynamics/Propagators/unitTestKeplerPropagator.h \
    Astrodynamics/ReferenceFrames/referenceFrameTransformations.h \
    Astrodynamics/ReferenceFrames/unitTestReferenceFrameTransformations.h \
    Astrodynamics/States/approximatePlanetPositions.h \
    Astrodynamics/States/approximatePlanetPositionsBase.h \
    Astrodynamics/States/approximatePlanetPositionsCircularCoplanar.h \
    Astrodynamics/States/approximatePlanetPositionsDataContainer.h \
    Astrodynamics/States/ephemeris.h \
    Astrodynamics/States/state.h \
    Astrodynamics/States/orbitalElements.h \
    Astrodynamics/States/orbitalElementConversions.h \
    Astrodynamics/States/keplerianElements.h \
    Astrodynamics/States/cartesianElements.h \
    Astrodynamics/States/cartesianPositionElements.h \
    Astrodynamics/States/cartesianVelocityElements.h \
    Astrodynamics/States/convertMeanAnomalyBase.h \
    Astrodynamics/States/convertMeanAnomalyToEccentricAnomaly.h \
    Astrodynamics/States/convertMeanAnomalyToHyperbolicEccentricAnomaly.h \
    Astrodynamics/States/unitTestApproximatePlanetPositions.h \
    Astrodynamics/States/unitTestKeplerianElements.h \
    Astrodynamics/States/unitTestCartesianElements.h \
    Astrodynamics/States/unitTestOrbitalElementConversions.h \
    Astrodynamics/MissionSegments/capturePhase.h \
    Astrodynamics/MissionSegments/deepSpaceManeuver.h \
    Astrodynamics/MissionSegments/escapeAndCapture.h \
    Astrodynamics/MissionSegments/escapePhase.h \
    Astrodynamics/MissionSegments/gravityAssist.h \
    Astrodynamics/MissionSegments/lambertTargeter.h \
    Astrodynamics/MissionSegments/librationPoint.h \
    Astrodynamics/MissionSegments/trajectoryDesignMethod.h \
    Astrodynamics/MissionSegments/unitTestDeepSpaceManeuver.h \
    Astrodynamics/MissionSegments/unitTestEscapeAndCapture.h \
    Astrodynamics/MissionSegments/unitTestGravityAssist.h \
    Astrodynamics/MissionSegments/unitTestLambertTargeter.h \
    Astrodynamics/MissionSegments/unitTestLibrationPoints.h \
    Basics/basicFunctions.h \
    Input/textFileReader.h \
    Input/fileReader.h \
    Input/twoLineElementData.h \
    Input/twoLineElementsTextFileReader.h \
    Input/unitTestTextFileReader.h \
    Input/unitTestTwoLineElementsTextFileReader.h \
    Mathematics/unitConversions.h \
    Mathematics/unitTestUnitConversions.h \
    Mathematics/basicMathematicsFunctions.h \
    Mathematics/cubicSplineInterpolation.h \
    Mathematics/unitTestBasicMathematicsFunctions.h \
    Mathematics/unitTestCubicSplineInterpolation.h\
    Mathematics/GeometricShapes/compositeSurfaceGeometry.h \
    Mathematics/GeometricShapes/geometricShape.h \
    Mathematics/GeometricShapes/singleSurfaceGeometry.h \
    Mathematics/GeometricShapes/surfaceGeometry.h \
    Mathematics/GeometricShapes/torus.h \
    Mathematics/GeometricShapes/sphereSegment.h \
    Mathematics/GeometricShapes/conicalFrustum.h \
    Mathematics/GeometricShapes/capsule.h \
    Mathematics/GeometricShapes/unitTestLawgsSurfaceGeometry.h \
    Mathematics/GeometricShapes/quadrilateralMeshedSurfaceGeometry.h \
    Mathematics/GeometricShapes/lawgsPartGeometry.h \
    Mathematics/LinearAlgebra/linearAlgebra.h \
    Mathematics/NumericalIntegrators/euler.h \
    Mathematics/NumericalIntegrators/integrator.h \
    Mathematics/NumericalIntegrators/rungeKutta4thOrderFixedStepsize.h \
    Mathematics/NumericalIntegrators/singleStepIntegrationMethods.h \
    Mathematics/NumericalIntegrators/stateDerivativeBase.h \
    Mathematics/NumericalIntegrators/unitTestRungeKutta4thOrderFixedStepsizeIntegrator.h \
    Mathematics/NumericalIntegrators/unitTestEulerIntegrator.h \
    Mathematics/RandomNumberGenerators/exponentialRandomNumberGenerator.h \
    Mathematics/RandomNumberGenerators/normalRandomNumberGenerator.h \
    Mathematics/RandomNumberGenerators/randomNumberGenerator.h \
    Mathematics/RandomNumberGenerators/uniformRandomNumberGenerator.h \
    Mathematics/RandomNumberGenerators/unitTestRandomNumberGenerator.h \
    Mathematics/RootFindingMethods/unitTestNewtonRaphson.h \
    Mathematics/RootFindingMethods/rootFinderBase.h \
    Mathematics/RootFindingMethods/rootFinder.h \
    Mathematics/RootFindingMethods/newtonRaphsonBase.h \
    Mathematics/RootFindingMethods/newtonRaphsonAdaptor.h \
    Mathematics/RootFindingMethods/newtonRaphson.h \
    Mathematics/Statistics/simpleLinearRegression.h \
    Mathematics/Statistics/unitTestSimpleLinearRegression.h \
    Output/writingOutputToFile.h
INCLUDEPATH += ./ \
    Applications \
    Astrodynamics \
    Astrodynamics/Bodies \
    Astrodynamics/EnvironmentModels \
    Astrodynamics/ForceModels \
    Astrodynamics/MomentModels \
    Astrodynamics/Propagators \
    Astrodynamics/ReferenceFrames \
    Astrodynamics/States \
    Astrodynamics/MissionSegments \
    Basics \
    External/Eigen-2.0.15 \
    Input \
    Mathematics \
    Mathematics/GeometricShapes \
    Mathematics/LinearAlgebra \
    Mathematics/NumericalIntegrators \
    Mathematics/RandomNumberGenerators \
    Mathematics/RootFindingMethods \
    Mathematics/Statistics \
    Output
