package:
  name: tudat
  version: 2.8.23

source:
  path: ../
#  git_url: ../
#  git_rev: cef926f39134ef2c4400124294ec1385c1c97fac

build:
  # A non-negative integer representing the build number of the package.
  #  Unlike the build string, the build_number is inspected by conda.
  #  Conda uses it to sort packages that have otherwise identical names
  #  and versions to determine the latest one. This is important because
  #  new builds that contain bug fixes for the way a package is built may be
  #  added to a repository.
  number: 2
  skip: true  # [win and vc<14]

requirements:
  build:
    # Tools required to build the package. These packages are run on the build
    # system and include things such as revision control systems (Git, SVN) make
    # tools (GNU make, Autotool, CMake) and compilers (real cross, pseudo-cross,
    # or native when not cross-compiling), and any source pre-processors.
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - cmake

outputs:
  - name: tudat
    build:
      ignore_run_exports:
        - m2w64-gcc-libs  # [win]
      run_exports:
        - cspice-cmake
        - sofa-cmake
        - tudat-resources
      detect_binary_files_with_prefix: true
      missing_dso_whitelist:
        - libgcc-ng
        - libstdcxx-ng
        - libm
        - libc
    requirements:
      host:
        # Packages that need to be specific to the target platform when the
        # target platform is not necessarily the same as the native build
        # platform
        - tudat-resources
        - boost-cpp=1.64.0
        - cspice-cmake
        - sofa-cmake
        - eigen
      run:
        # Packages required to run the package. These are the dependencies
        # that are installed automatically whenever the package is installed.
        # Package names should follow the package match specifications.
        - {{ pin_compatible('boost-cpp', max_pin='x.x') }}

    test:
      downstreams:
        - tudatpy

about:
  home: http://tudat.tudelft.nl/
  license: BSD
  license_family: BSD
  summary: A C++ platform to perform astrodynamics and space research
